import React from 'react'
import { Story, Meta } from '@storybook/react/types-6-0';

import {ItskButton, ItskButtonProps} from './itsk-button'
import {IconsSprite} from '../itsk-icon/IconsSprite'

const iconTypesArray = [
  "toggle_off-switch-filled" ,
  "toggle_on-switch-filled" ,
  "radio_off-circle-filled" ,
  "radio_on-circle-tor-filled" ,
  "checkbox_off-rectangle-filled" ,
  "checkbox_on-rectangle-filled" ,
  "checkbox_off-rectangle-outline" ,
  "checkbox_on-rectangle-outline" ,
  "checkbox_marker-check-outline" ,
  "radio_off-circle-outline" ,
  "radio_on-circle-outline" ,
  "radio_marker-circle-filled" ,
  "x-close-outline" ,
  "x-close-clear-rectangle-filled" ,
  "x-erase-clear-circle-filled" ,
  "x-erase-undo-clear-filled" ,
  "denied-banned-circle-slash-outline" ,
  "clock_round_ccw-time-history-circle-outline" ,
  "clock_round-time-circle-outline" ,
  "stop-round-rectangle-filled" ,
  "pause_round-parallel-line-filled" ,
  "play_round-triangle-right-filled" ,
  "stop-rectangle-square-filled" ,
  "pause-parallel-line-filled" ,
  "play-triangle-right-filled" ,
  "scroll-updown-arrow-filled" ,
  "triangle-down-arrow-filled" ,
  "triangle-up-arrow-filled" ,
  "group_min-minus-outline" ,
  "group_max-plus-outline" ,
  "group_round_min-minus-circle-filled" ,
  "group_round_max-plus-circle-filled" ,
  "group_square_min-minus-rectangle-filled" ,
  "group_square_max-plus-rectangle-filled" ,
  "question-help-outline" ,
  "question_square-rectangle-help-outline" ,
  "question_round-circle-help-filled" ,
  "info_octahedron-filled" ,
  "attention_triangle-filled" ,
  "attention_round-circle-filled" ,
  "attention_square-rectangle-outline" ,
  "move-arrow-outline" ,
  "zoom_out-minus-outline" ,
  "zoom_in-plus-outline" ,
  "magnifier-search-outline" ,
  "minimize-arrow-outline" ,
  "maximize-arrow-outline" ,
  "maximize-fullscreen-outline" ,
  "send-airplane-message-filled" ,
  "rotate_cw-redo-repeat-arrow-outline" ,
  "rotate_ccw-undo-return-arrow-outline" ,
  "refresh_cw-update-arrow-outline" ,
  "refresh_ccw-update-arrow-outline" ,
  "trash-bin-basket-filled" ,
  "unlock-unblock-off-filled" ,
  "lock-block-on-filled" ,
  "print-printer-send-image-filled" ,
  "exchange-bucket-update-updown-filled" ,
  "upload-arrow-line-up-file-filled" ,
  "download-arrow-line-down-file-filled" ,
  "link-attach-file-outline" ,
  "attach-paperclip-document-outline" ,
  "cut-scissors-cross-outline" ,
  "copy_text-sheet-square-filled" ,
  "copy_blank-sheet-square-filled" ,
  "new-document-sheet-filled" ,
  "save-memory-disk-filled" ,
  "edit_box-pencil-filled" ,
  "edit_line-pencil-filled" ,
  "edit-pencil-filled" ,
  "equal-line-parallel-outline" ,
  "less-left-chevron-arrow-outline" ,
  "more-right-chevron-arrow-outline" ,
  "more_equal-line-right-arrow-outline" ,
  "less_equal-line-left-arrow-outline" ,
  "not_equal-line-cross-outline" ,
  "chevrons_up-arrow-outline" ,
  "chevrons_right-arrow-outline" ,
  "chevrons_left-arrow-outline" ,
  "chevrons_down-arrow-outline" ,
  "chevron_up-arrow-outline" ,
  "chevron_down-arrow-outline" ,
  "chevron_right-arrow-outline" ,
  "chevron_left-arrow-outline" ,
  "arrow_corner_up_right-outline" ,
  "arrow_corner_up_left-outline" ,
  "arrow_corner_right_up-outline" ,
  "arrow_corner_right_down-outline" ,
  "arrow_corner_left_up-outline" ,
  "arrow_corner_left_down-outline" ,
  "arrow_corner_down_right-outline" ,
  "arrow_corner_down_left-outline" ,
  "arrow_upright-outline" ,
  "arrow_upleft-outline" ,
  "arrow_downright-outline" ,
  "arrow_downleft-outline" ,
  "arrow_down-outline" ,
  "arrow_up-outline" ,
  "arrow_right-outline" ,
  "arrow_left-outline" ,
  "roll_left-triangle-filled" ,
  "roll_right-triangle-filled" ,
  "roll_down-triangle-filled" ,
  "roll_up-triangle-filled" ,
  "arrow_upright-cell-outline" ,
  "sort_down-arrow-increase-outline" ,
  "sort_up-arrow-decrease-outline" ,
  "arrows_ccw-update-refresh-cycle-outline" ,
  "arrow_square_up-chevron-rectangle-filled" ,
  "arrow_square_down-chevron-rectangle-filled" ,
  "arrow_square_right-chevron-rectangle-filled" ,
  "arrow_square_left-chevron-rectangle-filled" ,
  "arrow_round_up-sign-circle-filled" ,
  "arrow_round_right-sign-circle-filled" ,
  "arrow_round_left-sign-circle-filled" ,
  "arrow_round_down-sign-circle-filled" ,
  "favorite_on-star-rating-filled" ,
  "favorite_off-star-rating-outline" ,
  "bookmark--tab-hold-filled" ,
  "pin_off-hold-outline" ,
  "pin_on-hold-outline" ,
  "notify_off-bell-ring-filled" ,
  "notify_on-bell-ring-filled" ,
  "visible_off-eye-view-outline" ,
  "visible_on-eye-view-outline" ,
  "calendar_date-filled" ,
  "calendar-date-filled" ,
  "calendar_today-date-filled" ,
  "filter_small-conus-filled" ,
  "filter_clear-conus-x-filled" ,
  "filter-conus-filled" ,
  "sort_ascending-row-line-outline" ,
  "sort_descending-row-line-outline" ,
  "menu_burger-line-list-filled" ,
  "grid_big-line-cell-filled" ,
  "grid_small-line-cell-filled" ,
  "cards-rectangle-filled" ,
  "checklist-line-row-filled" ,
  "list_bullet-line-mark-row-filled" ,
  "list-line-row-filled" ,
  "user_delete-x-clear-filled" ,
  "users-minus-filled" ,
  "user_add-plus-filled" ,
  "user_delete-minus-filled" ,
  "user_check-filled" ,
  "user-filled" ,
  "color-palette-paint-filled" ,
  "light_on-sun-day-filled" ,
  "light_off-moon-night-filled" ,
  "light_off-bulb-dark-filled" ,
  "light_on-bulb-filled" ,
  "settings_slider_vertical-tune-filled" ,
  "settings_slider_horizont-tune-filled" ,
  "settings-star-gear-filled" ,
  "menu_more_horizont_small-point-circle-dot-filled" ,
  "menu_more_vertical-point-circle-dot-filled" ,
  "menu_more_horizont-point-circle-dot-filled" ,
  "menu_full-point-circle-dot-filled" ,
  "file-outline" ,
  "file_pdf-outline" ,
  "file_xls-outline" ,
  "file_doc-outline" ,
  "file-filled" ,
  "file_txt-text-filled" ,
  "file_image-picture-filled" ,
  "file_pdf-filled" ,
  "file_xls-excell-filled" ,
  "file_doc-word-filled" ,
  "worker-mer-filled" ,
  "well-pump-outline" ,
  "ruble-money-outline" ,
  "book-guide-filled" ,
  "map-point-dot-filled" ,
  "crosshair-aim-filled" ,
  "equipment-motor-filled" ,
  "repairs-wrench-settings-filled" ,
  "chess-filled" ,
  "fire-gas-burn-filled" ,
  "faucet-water-oil-filled" ,
  "drop-water-oil-filled" ,
  "assembly-motor-outline" ,
  "motor-outline" ,
  "pump-outline" ,
  "cutter-squre-rectangle-outline" ,
  "drop_half-liquid-filled" ,
  "dashboard-speed-value-outline" ,
  "wrench-repair-filled" ,
  "layers-sheet-filled" ,
  "database-store-filled" ,
  "trending_up-graph-chart-arrow-outline" ,
  "trending_down-graph-chart-arrow-outline" ,
  "activity-pulse-outline" ,
  "energy-lightning-filled" ,
  "home-house-filled" ,
  "chart_tree_horizont-graph-filled" ,
  "chart_tree_vertical_round-graph-filled" ,
  "chart_tree_vertical_square-graph-filled" ,
  "chart_bar-graph-rand-outline" ,
  "chart_bar-graph-desc-outline" ,
  "chart_line-graph-outline" ,
  "chart_pie-graph-circle-outline"]
export default {
  title: 'Components/ItskButton',
  component: ItskButton,
  argTypes: {
    leftIcon: {
      control: {
        type: 'select',
        options: iconTypesArray
      }
    },
    rightIcon: {
      control: {
        type: 'select',
        options: iconTypesArray
      }
    },
    onClick: {
      action: 'clicked'
    }
  }
} as Meta

const Template: Story<ItskButtonProps> = (args) => {
  return (
    <>
      <IconsSprite/>
      <ItskButton {...args} theme={"success"}/>
      <br/>
      <ItskButton {...args} theme={"error"}/>
      <br/>
      <ItskButton {...args} theme={"primary"}/>
      <br/>
      <ItskButton {...args} theme={"secondary"}/>
      <br/>
      <ItskButton {...args} theme={"warning"}/>
      <br/>
      <ItskButton {...args} theme={"default"}/>

    </>
    )
}

export const defaultButton = Template.bind({})
defaultButton.args = {
  children: 'Simple button',
  leftIconClassName: 'margin-r-2',
  rightIconClassName: 'margin-l-2',
  className: 'margin-b-2'
}
